services:
  - type: web
    name: geo-sync-app
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
        sync: false
      - key: NEXT_PUBLIC_SHOW_DEBUG
        value: "false"
